analytics: {}
color:
  brandColors:
    - '#C8D0D8'
    - '#800808'
    - '#687880'
    - '#C03028'
    - '#000000'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0.069257
name: Guardians Monastery
opengraph: {}
purpose: {}
typography_spectrum: 0.34375
