analytics: {}
color:
  brandColors:
    - '#C8D0D8'
    - '#800808'
    - '#687880'
    - '#C03028'
    - '#000000'
  brandStrength: 0.70777
  lightness: 0
  rhythmicContrast: 0.615709
  saturation: 0.455236
cta: {}
layout_spectrum: 0.069257
name: Guardians Monastery
opengraph: {}
purpose: {}
typography_spectrum: 0.355574
