analytics: {}
color:
  brandColors:
    - '#C8D0D8'
    - '#800808'
    - '#687880'
    - '#C03028'
    - '#000000'
  brandStrength: 0.338682
  lightness: 0.050676
  rhythmicContrast: 0.849662
  saturation: 0.724662
cta: {}
layout_spectrum: 0.069257
name: Guardians Monastery
opengraph: {}
purpose: {}
typography_spectrum: 0.355574
